# Generated by Django 5.1.6 on 2025-03-29 20:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('flag', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(default='', max_length=500)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(default='', max_length=500)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('home_team_last_five_results', models.JSONField(blank=True, null=True)),
                ('away_team_last_five_results', models.JSONField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('home_wins_probability', models.FloatField(blank=True, null=True)),
                ('away_wins_probability', models.FloatField(blank=True, null=True)),
                ('date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='', max_length=10)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.competition')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='api.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='api.team')),
            ],
            options={
                'indexes': [models.Index(fields=['away_team', 'home_team'], name='api_match_away_te_724d28_idx'), models.Index(fields=['competition'], name='api_match_competi_68f9c1_idx')],
            },
        ),
    ]
