# Generated by Django 5.1.6 on 2025-04-23 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('winner', 'Who will win'), ('both_score', 'Will both teams score'), ('first_score', 'Who will score first'), ('draw', 'Will there be a draw')], max_length=20)),
                ('answer', models.CharField(choices=[('1', 'Home'), ('2', 'Away'), ('yes', 'Yes'), ('no', 'No'), ('without_heads', 'Without heads')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
        ),
    ]
