# Generated by Django 5.1.6 on 2025-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('surface', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(default='', max_length=500)),
            ],
        ),
    ]
