# Generated by Django 5.1.6 on 2025-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_match_id_match_match_id_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
