# Generated by Django 5.1.6 on 2025-05-26 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stadium'),
        ),
    ]
