# Generated by Django 5.1.6 on 2025-05-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_team_stadium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
