# Generated by Django 5.1.6 on 2025-03-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_team_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_wins_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_wins_probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
