# Generated by Django 5.1.6 on 2025-05-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_stadium_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
