# Generated by Django 5.1.6 on 2025-03-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_match_away_wins_probability_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['away_team', 'home_team'], name='api_match_away_te_724d28_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['competition'], name='api_match_competi_68f9c1_idx'),
        ),
    ]
