# Generated by Django 5.1.6 on 2025-05-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_stadium_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='founded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
