# Generated by Django 5.1.6 on 2025-06-03 16:18

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_team_founded'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_colors', jsonfield.fields.JSONField()),
                ('home_team_startXI', jsonfield.fields.JSONField()),
                ('home_team_substitutes', jsonfield.fields.JSONField()),
                ('home_team_coach_name', models.CharField(max_length=100)),
                ('away_team_colors', jsonfield.fields.JSONField()),
                ('away_team_startXI', jsonfield.fields.JSONField()),
                ('away_team_substitutes', jsonfield.fields.JSONField()),
                ('away_team_coach_name', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid', to='api.match')),
            ],
        ),
    ]
