# Generated by Django 5.1.6 on 2025-06-04 15:22

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_matchgrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchgrid',
            name='away_team_colors',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='matchgrid',
            name='home_team_colors',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
